# Generated by Django 5.2.1 on 2025-05-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='created_at',
        ),
    ]
