# Generated by Django 5.2.3 on 2025-06-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playlist_created_at_song_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={},
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='songs',
            new_name='song',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='created_at',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('playlists', models.ManyToManyField(blank=True, related_name='user_profiles', to='main.playlist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['user'],
            },
        ),
    ]
